autoload/clap/provider/files.vim
The files provider used a dict to organize the tools it was searching. Iterating over the dict did not give items in the same order as they appeared in the file. This caused `git` to be used before `fd`.
This PR fixes the issue by switching from a dict to a list.
=> Fix files provider to search tools in order they are listed

README.md, autoload/clap/popup.vim
This addresses the documentation ambiguity mentioned in #34.
I was unsure whether to mark off the <kbd>Ctrl</kbd><kbd>h</kbd> bit as done. It works for me in NeoVim but perhaps it isn't working everywhere? I added that as a separate commit so it would be easy to drop if it's not appropriate.
=> Use todo-list syntax instead of mix and match lists

README.md, autoload/clap/api.vim, autoload/clap/dispatcher.vim, autoload/clap/floating_win.vim, autoload/clap/handler.vim, autoload/clap/impl.vim, autoload/clap/init.vim, autoload/clap/popup.vim, autoload/clap/provider/grep.vim, autoload/clap/provider/marks.vim, autoload/clap/util.vim, syntax/clap_marks.vim
=> Add preview for marks

autoload/clap/provider/grep.vim
Fixed an issue where on windows (in nvim) where ripgrep will wait for input from stdin instead of implicitly using current directory.
When I tried to use the grep functionality it didn't work for me. After some time I noticed that while the popup is going, the ripgrep process was still running.
Turns out, on windows and nvim the ripgrep process will wait for stdin to provide data instead of implicitly using the current directory. (source: https://github.com/mhinz/vim-grepper/issues/205#issuecomment-497941276)
This change should not be breaking for other environments.
=> Fixed grep provider on windows nvim

CHANGELOG.md, autoload/clap.vim, autoload/clap/api.vim, autoload/clap/filter.vim, autoload/clap/floating_win.vim, autoload/clap/init.vim, autoload/clap/popup.vim, autoload/clap/provider/marks.vim, doc/clap.txt
Close #73
The default is `nil` style if no expected font is found as not every font and terminal emulator can render these symbols perfectly. You can use it when you are satisfied with the rendered result.
`let g:clap_search_box_border_style = 'curve'`:
`let g:clap_search_box_border_style = 'nil'`:
I'm using kitty with FuraCode Nerd Font.
=> Add search box border symbol

autoload/clap/provider/yanks.vim
**Problem**: Currently, yank window opens even though yanks provider is
disabled through the variable `g:clap_enable_yanks_provider`
**Fix**: if yanks provider is disabled, close the provider through clap#exit
=> Prevent yanks window if disabled

autoload/clap/provider/yanks.vim, doc/clap.txt
Set the minimum length of yanked text to be stored in yanks stack. This
can be configured through a variable 'g:clap_provider_yanks_min_len'.
This feature is disabled by default(set to 1).
=> yanks: set minimum length to store in yanks stack

autoload/clap/impl.vim, autoload/clap/util.vim
Use matchaddpos() instead of nvim_buf_add_highlight()
=> Don't let the highlight of sign override the fuzzy matched highlights

autoload/clap.vim, autoload/clap/api.vim, autoload/clap/dispatcher.vim, autoload/clap/filter.vim, autoload/clap/forerunner.vim, autoload/clap/impl.vim, autoload/clap/indicator.vim, autoload/clap/job.vim, autoload/clap/util.vim
First step of the optimization, currently only the small scale searching is fully supported. The
benefits of the forerunner jobs are:
- avoid the redraw caused by job.
- don't have to spawn a new job on each of your type.
Related: #98
=> Spawn a forerunner job when initializing the display window

autoload/clap/util.vim
I ran into a issue when fiddling with a provider for changing directories, where the enable_rooter function reverted the changes.
=> Dont cd back if sink changes dir

autoload/clap/impl.vim, autoload/clap/sign.vim
based on https://github.com/vim/vim/commit/7257073043252c2e01c8e168e6842a1121797243
fixed #130
=> Fix sign group name in vim's popup

autoload/clap/impl.vim
When using external async filters vim-clap will revert back to the sync internal filter unless the provider returns more than 10000 entries. 
From what I could tell internally what is happening is that vim-clap is storing some cache in memory and if there is cache it will always run synchronously. This results in losing fuzzy matching when using external filters(unless you have the internal one written in phyton).
With this PR if there is a external filter set then even if there is cache the filtering will be done async.
=> Fix async external filter on typing falling back to sync

pythonx/clap/fuzzymatch-rs/src/lib.rs
The required length of those vectors is the exact length of `ranked` vector. It is faster and takes less memory to allocate vector once with known capacity than automatic resize through `push()`.
=> Change Vec::new() to Vec::with_capacity()

CHANGELOG.md, autoload/clap/impl.vim, autoload/clap/provider/tags.vim
- Need the API exposed by vista.vim https://github.com/liuchengxu/vista.vim/commit/5538f9bc62beecb68f4ab1be63f92e77bd2c93f0
-  Hide the preview window when the input is empty and has no matches.
=> Add preview for tags provider

autoload/clap/helper.vim, pythonx/clap/Makefile
When trying build rust module for vim-clap I got error:
```bash
pythonx/clap/fuzzymatch-rs on > master is 📦 v0.1.0 via 🦀 v1.39.0
[ 14:13:13 ]  ❯ cargo build --release
Compiling pyo3 v0.8.3
error: failed to run custom build command for `pyo3 v0.8.3`
Caused by:
process didn't exit successfully: `/Users/d.evsyukov/.vim/plugged/vim-clap/pythonx/clap/fuzzymatch-rs/target/release/build/pyo3-eb13f65051f8e97f/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Error: pyo3 requires a nightly or dev version of Rust.', /Users/d.evsyukov/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.8.3/build.rs:542:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
for building this code we need to use nightly rust chanel.
=> Using +nightly chanel for building rust

CHANGELOG.md, autoload/clap.vim, autoload/clap/api.vim, autoload/clap/filter.vim, autoload/clap/forerunner.vim, src/main.rs
Close #98
When the result set is too large for the built-in sync filter, and the furerunner job is completed, save the results to a tmp file instead of always running the heavy command again, which could be 2x faster.
```bash
$ cd ~ && fd --type f > home.txt
$ time /Users/xlc/.vim/plugged/vim-clap/target/release/maple "srli" --input /Users/xlc/home.txt --number 96
real	0m1.674s
user	0m1.640s
sys	0m0.093s
$ time fd --type f | /Users/xlc/.vim/plugged/vim-clap/target/release/maple "srli" --number 96
real	0m3.173s
user	0m6.310s
sys	0m13.075s
```
This commit 3557163 using rayon's `par_lines` gains 3x faster again than reading file using std lib.
```bash
$ time /Users/xlc/.vim/plugged/vim-clap/target/release/maple "srli" --input /Users/xlc/home.txt --number 96
real	0m0.491s
user	0m2.838s
sys …
```
=> Cache the result of forerunner to a tmp file

CHANGELOG.md, autoload/clap.vim, autoload/clap/api.vim, autoload/clap/provider/blines.vim, autoload/clap/provider/buffers.vim, autoload/clap/provider/command.vim, autoload/clap/provider/command_history.vim, autoload/clap/provider/commits.vim, autoload/clap/provider/grep.vim, autoload/clap/provider/jumps.vim, autoload/clap/provider/lines.vim, autoload/clap/provider/marks.vim, autoload/clap/provider/quickfix.vim, autoload/clap/provider/registers.vim, autoload/clap/provider/tags.vim
Setting `filetype` would also trigger some other filetype related hooks, which is normaly unexpected.
=> Add highlight for displaying buffer by setting syntax option

README.md, autoload/clap.vim, autoload/clap/forerunner.vim, autoload/clap/maple.vim, autoload/clap/spinner.vim, doc/clap.txt
- Add the forerunner job status sign:
- `!files`: the forerunner job is not finished yet. If you type something rightnow, the result is incomplete and uncertain.
- `*files`: the forerunner job is done, now the responose of vim-clap should be fast and deterministic.
The forerunner job is normally super fast and imperceptible unless you have 1 million items, in which case it may take seconds but Vim/NeoVim is still well responsive and you won't feel any typing lag.
- Add the delay for running maple.
I proposed serveral solutions for the perfornce improvement in #140. Although I have not tried all of them, the `maple` extension written in Rust already works very well. If you want to a performant vim-clap, please [install Rust](https://www.rust-lang.org/tools/install) and then run `:call …
=> Add forerunner job status sign and a delay timer for running maple

README.md, autoload/clap/popup.vim, doc/clap.txt
For neovim, `<C-u>` will clear inputs, but vim won't.
This PR adds `<C-u>` mapping to vim's popup for clearing inputs.
=> Add <C-U> mapping to popup for clearing inputs

syntax/clap_files.vim
A capitalised term attribute (None) results in a `E254: Cannot allocate color None` error message when running `:Clap files`. This pull request fixes that issue by uppercasing the attribute.
=> Uppercase the NONE term attribute

CHANGELOG.md, autoload/clap/dispatcher.vim
=> Use s:loaded_size instead of line_count of neovim as we don't clear the old content

CHANGELOG.md, PROVIDER.md, autoload/clap.vim, autoload/clap/debugging.vim, autoload/clap/dispatcher.vim, autoload/clap/filter.vim, autoload/clap/forerunner.vim, autoload/clap/highlight.vim, autoload/clap/impl.vim, autoload/clap/maple.vim
- When people clear the input, the previous job could be still unfinished. https://github.com/liuchengxu/vim-clap/pull/248#issuecomment-575909963
- Use the capacity of filter globally.
- Split out highlight.vim.
=> Skip the job processing if current input is empty

CHANGELOG.md, autoload/clap/filter/external.vim
=> Support skim as the external filter

README.md
I think it's worth including this variable in the readme. So far, it was only documented in the changelog and it had a major impact on the UX (changing vim-clap position to be relative to the active window by default).
=> Add readme section on clap_layout

autoload/clap/cache.vim, autoload/clap/provider/help_tags.vim, doc/clap.txt
Hi @liuchengxu,
I add a provider to list help tags.
I implement cache for better performance, but it seems no file cache folder in Clap, therefore, I use `fnamemodify($MYVIMRC, ':p:h')` as my default cache folder.
If you have better place, just let me know.
And, I have no idea how to implement preview,  so, no preview at this moment.
=> Add help tags provider

CHANGELOG.md, README.md, autoload/clap/cache.vim, autoload/clap/provider/help_tags.vim, autoload/clap/provider/providers.vim, doc/clap-support.txt, doc/clap.txt, src/cmd.rs, src/cmd_impl.rs, src/main.rs
Follow up of #248
Implement the helptags in maple and other various nits. The result of maple is more complete compared with the vimscript impl which differentiates the `hello.txt` and `hello.cnx`.
=> Impl maple helptags

INSTALL.md
Since `clap#helper#download_binary()` has been changed to `clap#installer#download_binary()`, "Install.md" also needs to be updated.
=> doc: Update the "Download the pre-built binaries"

CHANGELOG.md, README.md, autoload/clap/navigation.vim, autoload/clap/provider/filer.vim, doc/clap.txt, ftplugin/clap_input.vim
- Add some normal mappings for neovim to explore the results easier.
- Add scroll to top/bottom function.
Changed:
-  `<Esc>` in insert mode will not exit the clap but back to the normal mode.
Ref #51
=> Support normal mode mappings for neovim

autoload/clap/popup/move_manager.vim
Currently clap does not accept non-ascii characters for filtering on Vim (#129). I enabled that by using `strchar*()` functions instead of byte index. `s:cursor_idx` has been changed to indicate character index instead of byte index.
Since `strcharpart()` does not throw error for out-of-bound indexes, the source have gotten simpler.
Also, I fixed that the cursor in popup was not highlighted properly if the cursor contains multi-byte characters.
=> Support multibyte input for popup filter

CHANGELOG.md, autoload/clap/popup/move_manager.vim, autoload/clap/themes.vim, doc/clap.txt
* Make the cursor in popup filter block-shaped when `g:clap_popup_cursor_shape == ''`.
* I feel it deserves to be default, so make it default.
* I noticed `<Del>` does not work in popup filter, so make it work as it works on neovim.
before:
after:
=> Block cursor for popup filter

CHANGELOG.md, autoload/clap.vim, autoload/clap/popup.vim, doc/clap.txt
=> Add popup preview border

CHANGELOG.md, INSTALL.md, autoload/clap/filter/async/dyn.vim, crates/fuzzy_filter/src/lib.rs, crates/maple_cli/src/cmd/blines.rs, crates/maple_cli/src/cmd/filter/dynamic.rs, crates/maple_cli/src/cmd/filter/mod.rs, crates/maple_cli/src/cmd/grep.rs, crates/maple_cli/src/cmd/helptags.rs, crates/maple_cli/src/cmd/mod.rs, src/main.rs
Fix https://github.com/liuchengxu/vim-clap/pull/383#issuecomment-611453184
Also fix some errors found in maple.
=> Don't match filepath in grep2

CHANGELOG.md, Cargo.lock, INSTALL.md, autoload/clap/filter.vim, autoload/clap/filter/sync/python.vim, autoload/clap/highlight.vim, autoload/clap/provider/files.vim, crates/Cargo.toml, crates/fuzzy_filter/Cargo.toml, crates/fuzzy_filter/src/content_filtering.rs, crates/fuzzy_filter/src/lib.rs, crates/fuzzy_filter/src/source.rs, crates/maple_cli/src/cmd/blines.rs, crates/maple_cli/src/cmd/filter/dynamic.rs, crates/maple_cli/src/cmd/filter/mod.rs, crates/maple_cli/src/cmd/grep.rs, crates/maple_cli/src/cmd/mod.rs, crates/maple_cli/src/lib.rs, crates/printer/Cargo.toml, crates/printer/src/lib.rs, doc/clap-support.txt, pythonx/clap/fuzzymatch-rs/Cargo.lock, pythonx/clap/fuzzymatch-rs/Cargo.toml, pythonx/clap/fuzzymatch-rs/src/lib.rs, pythonx/clap/fzy.py, release.sh
Also support filter the file name only. You have to use the python dynamic module, or you are using the cached content with dyn filter, `:Clap files +name-only`.
`:Clap files`:
`:Clap files +name-only`:
Close #379
Also tweak the icon highlight offset on Python and Rust side instead of inside vim.
=> Split out Printer crate

autoload/clap/provider/git_diff_files.vim
- Enable `git diff` preview for `on_move` for `git_diff_files` provider.
- Set function as local variable if need to extend to `on_enter` event.
=> feat(git_diff_files): Enable Git Diff Preview

autoload/clap/floating_win.vim, autoload/clap/popup.vim
a18bcf3 only partially fixes #400; this PR also defaults to `nospell` for the display and preview windows.
=> Fix default to nospell in display and preview windows

autoload/clap/installer.vim, autoload/clap/maple.vim, install.ps1
Fix #404 
- Quote the path to install.ps1 so that it will handle spaces correctly.
- Add `-ExecutionPolicy ByPass`  as a parameter to powershell to be able to execute powershell script when by default win10 prevent you to do this.
- Add Tls12 to security protocol to be able to download the pre-built binary.
=> Fix binary installation on Windows

CHANGELOG.md, autoload/clap/debugging.vim, autoload/clap/dispatcher.vim, autoload/clap/filter/async/dyn.vim, autoload/clap/filter/async/external.vim, autoload/clap/filter/sync/viml.vim, autoload/clap/forerunner.vim, autoload/clap/highlight.vim, autoload/clap/impl.vim, autoload/clap/job.vim, autoload/clap/job/stdio.vim, autoload/clap/maple.vim, autoload/clap/provider/filer.vim, autoload/clap/provider/grep.vim, autoload/clap/provider/grep2.vim, autoload/clap/provider/help_tags.vim, autoload/clap/provider/proj_tags.vim, crates/maple_cli/src/cmd/cache.rs, crates/maple_cli/src/cmd/grep.rs
Fix the issue of job cmd when `cmd` is String and it contains spaces.
Initially reported in https://github.com/liuchengxu/vim-clap/issues/404#issuecomment-615959962.
cc @ErrEoE @TissueFluid
=> Use List instead of String in job cmd

CHANGELOG.md, Cargo.lock, crates/maple_cli/Cargo.toml, crates/maple_cli/src/cmd/check_release/download.rs, crates/maple_cli/src/cmd/check_release/github.rs, crates/maple_cli/src/cmd/check_release/mod.rs
=> Add progress bar to the binary download

syntax/clap_proj_tags.vim
Improvement for 
['Some of the text is hard to identify in dark theme #450'](https://github.com/liuchengxu/vim-clap/issues/450)
One liner.
=> Update the highlight for proj_tags #450

autoload/clap/api.vim, autoload/clap/popup.vim, autoload/clap/popup/move_manager.vim, autoload/clap/provider/windows.vim
Uses window IDs instead of buffers. Also fixes active window display.
=> Don't show Clap windows in `:Clap windows`

autoload/clap/provider/git_diff_files.vim
fixes #401
- Enable max height for preview window
- #401 (comment)
- Truncate amount of lines displayed in unified format using `-U0`
- Check for multiple types of diff types
- Modified
- Deleted staged and unstaged
- Added staged and unstaged
- Added or deleted with no content
- Comparing tip and index with current branch
- ` --cached file`
- ` -- file`
=> fix(git_diff_files): Fix Diff Preview Files

autoload/clap/provider/yanks.vim
My setup: NVIM v0.3.7
After updating my install after not doing so for a few months, I started seeing an error every time I launched `nvim` and yanked: `Error not enough arguments passed to bufname`. It looks like the change that is biting me was made here: https://github.com/liuchengxu/vim-clap/pull/324
I read the nvim docs, and while it does say ["If {expr} is omitted the current buffer is used."](https://neovim.io/doc/user/eval.html#bufname()), that has not been true in my experience. 
I added a small change, which resolves the issue for me, and I believe preserves the intended functionality, judging by this line in the nvim docs: [""" or "%" can be used for the current buffer..."](https://neovim.io/doc/user/eval.html#bufname()). 
Thought I would try to contribute back to the community …
=> Pass args to bufname to resolve nvim error

autoload/clap/provider/history.vim
History provider supports open action, but action is not used in sink func.
=> Fix history provider open action support

CHANGELOG.md, PROVIDER.md, autoload/clap/impl/on_move.vim, autoload/clap/provider/bcommits.vim, autoload/clap/provider/commits.vim, autoload/clap/provider/filer.vim, crates/pattern/src/lib.rs, crates/stdio_server/src/filer.rs, crates/stdio_server/src/session/context.rs, crates/stdio_server/src/session/handler/on_move.rs, crates/stdio_server/src/types.rs, crates/utility/src/lib.rs
- Add a general `on_move_async` for clap provider.
- Imple async preview for `commits` and `bcommits` using `on_move_async`.
- Change `on_move` of `filer` to `on_move_async`.
=> Add on_move_async property

autoload/clap/provider/windows.vim
The `:Clap windows` provider's sink function passed the user's choice
down to parse_win(), which then ignored it and instead tried to fetch
the choice from the clap menu (which no longer exists at this point).
As a result, Vim throws the following exception when the user chooses
any item from the `:Clap windows` menu and thereby calls parse_win():
vim-clap: clap#handler#sink: Vim(return):E684: list index out of range: 2, throwpoint:function clap#handler#sink[12]..350[1]..clap#rooter#run_heuristic[4]..348[3]..385[1]..<SNR>508_parse_win, line 2
=> parse_win() ignored sink and tried to getcurline()

CHANGELOG.md, autoload/clap/installer.vim
On Windows:
* Vim's `term_start()` executes a command directly (not on a shell), so you need to add `cmd.exe /c` to the command if you use `&&` etc.
* Still using nightly Rust.
* `cargo build` runs on wrong directory when building Python dynamic module.
* The name of the built dynamic module is wrong.
This is a PR to fix them.
=> Fix `:Clap install-binary` does not work correctly on Windows

autoload/clap/provider/filer.vim
Option 'shellslash' will be tested having 'win32'.
Mixed seperators will be accepted like vim does on 'win32'.
=> Use correct path seperator on windows.

doc/clap.txt
It seems `g:clap_search_box_border_style` will be used as a key of `g:clap_search_box_border_symbols`, which is a `Dict`. `g:clap_search_box_border_style` itself should be a `String`.
=> Fix docs of g:clap_search_box_border_style

autoload/clap/provider/git_diff_files.vim
Closes #506 
`systemlist(git ...)` doesn't seem to respect `enable_rooter`, both diff files and previews are retrieved from the current directory, not from the project root. So `enable_rooter` doesn't really run the needed `source` command from the project root, and it misleads the `sink`.
Stop running `source` from the project root seems a simple solution. It works well for me no matter vim is started from the project root or not.
=> fix git_diff_files not running from project root (#506)

autoload/clap/selection.vim
Fixes plugins like `vim-mrufiles`.
=> Fix typo/bug g:get_opaque_line -> s:get_opaque_line

crates/matcher/extracted_fzy/src/lib.rs, pythonx/clap/scorer.py
Hey,
This PR is a request for feedback regarding the implementation of smart-case filtering. As a reminder, in vim the `'smartcase'` option makes searching with a lower-case input case-insensitive, but whenever the input contains an uppercase letter the search becomes case-sensitive. This improves results a lot when there is a known upper-case letter in the filter input.
This is also listed as a [possible improvement](https://github.com/jhawthorn/fzy/blob/master/ALGORITHM.md#case-sensitivity) to the original fzy algorithm.
Without smart-case, the desired target in placed in 12th position by the scoring function:
With smart-case, the target in first position without unwanted targets:
This PR is a proof of concept, it only implements the filtering in the python scorer and is not optional. …
=> [WIP] Smart-case

autoload/clap/dispatcher.vim, autoload/clap/job/daemon.vim, autoload/clap/job/stdio.vim
When `job_start()` was first called by vim-clap in vim8, preview and Clap filer were not working.
The reason is that the job id in vim8 starts at 0, but the condition of whether the job exists or not is wrong.
To check the first id of the job in vim8, I ran the following command to verify it.
```
vim -u NONE -U NONE
echo ch_info(job_getchannel(job_start('ls')))
```
The above command outputs the following
```
{'status': 'open', 'id': 0, 'in_io': 'pipe', 'err_mode': 'NL', 'in_status': 'open', 'out_io': 'pipe', 'err_io': 'pipe', 'err_status': 'open', 'out_timeout': 2000, 'out_status': 'open', 'out_mode':
'NL', 'in_mode': 'NL', 'in_timeout': 2000, 'err_timeout': 2000}
```
So I changed the conditions for the existence of job in vim8.
=> Fix file preview and Clap filer in vim8

CHANGELOG.md, autoload/clap/provider/command.vim, syntax/clap_command.vim
Quick improvements for the default `command` provider:
- Style: Parse & render each command instead of feeding `execute('command')` directly into clap
- Behavior: if a command has 0 arguments, it is executed immediately; otherwise, the user is put in command-mode with `:CommandName<space>` pre-filled so they can enter additional arguments
- Style: commands with 0 arguments have their argument highlighted with `WarningMsg` to denote they will be executed immediately
@liuchengxu This is ready for merging as it is, I wanted to do more but the rest can wait.
Before:
After:
=> Improve command provider

autoload/clap.vim, autoload/clap/api.vim, autoload/clap/provider/blines.vim, autoload/clap/provider/buffers.vim, autoload/clap/provider/colors.vim
This fixes a bug that I noticed in [barbar.nvim](https://github.com/romgrk/barbar.nvim). Barbar has a feature that a new buffer is opened next in order to the current buffer. The current clap behavior for restoring the current window is:
- Close clap window, letting vim decide which window to focus back *triggering autocommands*
- If the window isn't the right one, switch windows *without triggering autocmd* (`clap.start.goto_win()`)
This makes it that the last current buffer from any other plugin's perspective is the one to which vim focused back. This solves the issue.
=> fix: trigger autocmmands correctly when restoring window

autoload/clap/floating_win.vim, autoload/clap/init.vim, autoload/clap/layout.vim
Closes #516 
Pros:
- Resizing while clap is closed now works
Cons:
- Resizing while clap is open now segfaults (neovim bug)
I think it's still preferable to do this, I'm guessing most people don't resize while clap is open.
Source:
```
(gdb) f 4
#4  0x000056238641ce93 in msg_scroll_flush () at ../src/nvim/message.c:2229
2229	    assert(pos_delta >= 0);
```
Known issue: https://github.com/neovim/neovim/issues/12432
=> fix: resize on neovim

.gitignore, CHANGELOG.md, autoload/clap/debugging.vim, autoload/clap/filter.vim, autoload/clap/filter/sync/lua.vim, lua/fzy_filter.lua, lua/fzy_impl.lua
Close #565
Thanks to https://github.com/swarn/fzy-lua, the basic fzy Lua support in clap is much easier. The next step might be adding a user-friendly way to also support your https://github.com/romgrk/fzy-lua-native @romgrk . Let me know if you have any ideas about that.
~I have tested this PR against the latest neovim, but not sure I'll spend more time making it work with the older neovim and vim.~
Now it works with both latest neovim and vim.
=> Initial support for fzy lua

CHANGELOG.md, README.md, autoload/clap/provider/providers.vim
Add the providers defined via global variable into the `providers` provider, which means you can see the global variable type providers when you call `:Clap` now. But you have to define `description` explicitly otherwise they won't be found, for example,
```vim
let g:clap_provider_tasks = {
\ 'source': function('TaskListSource'),
\ 'sink': function('TaskListSink'),
\ 'description': 'List various tasks',
\ }
```
=> Add the providers defined using gloabl variable in providers provider

CHANGELOG.md, autoload/clap/filter.vim, autoload/clap/filter/sync/python.vim, autoload/clap/maple.vim, autoload/clap/provider/filer.vim, crates/filter/src/dynamic.rs, crates/filter/src/lib.rs, crates/filter/src/source.rs, crates/maple_cli/src/cmd/blines.rs, crates/maple_cli/src/cmd/filter.rs, crates/maple_cli/src/cmd/grep.rs, crates/maple_cli/src/cmd/tags.rs, crates/matcher/src/lib.rs, crates/printer/src/lib.rs, crates/source_item/src/lib.rs, crates/stdio_server/src/session/handler/on_typed.rs, doc/clap.txt, pythonx/clap/fuzzymatch-rs/src/lib.rs, pythonx/clap/fzy.py
Introduce an additional `Bonus` for the result of the base algorithm(fzy, skim, etc), e.g., add a bonus score to the match that hits the elements in the file name when the source item is a path. This PR makes `+name-only` kind of duplicated in some sense. cc @svermeulen
Currently, we just have one Bonus, we can have multiple Bonuses at the same time in the future which will help #542.
Before:
With this PR:
If the Lua filter is also available(using neovim or vim with `+lua`), you need to add `let g:clap_force_python = v:true` in your vimrc to choose the Python filter for using this, for this improvement is only implemented on the Rust side and you need to compile the Python dynamic module too.
Close #561
=> Add a bonus for matches in filename

CHANGELOG.md, autoload/clap/client.vim, autoload/clap/impl/on_move.vim, autoload/clap/provider/help_tags.vim, build.rs, crates/maple_cli/src/cmd/cache.rs, crates/maple_cli/src/light_command.rs, crates/printer/src/lib.rs, crates/stdio_server/src/env.rs, crates/stdio_server/src/lib.rs, crates/stdio_server/src/session/context.rs, crates/stdio_server/src/session/handler/mod.rs, crates/stdio_server/src/session/handler/on_move.rs, crates/stdio_server/src/types.rs, crates/upgrade/src/lib.rs, crates/utility/src/lib.rs
=> Add preview support for help_tags

crates/printer/src/lib.rs, crates/stdio_server/src/lib.rs, crates/stdio_server/src/session/handlers/mod.rs, crates/stdio_server/src/session/handlers/on_move.rs, crates/stdio_server/src/session/mod.rs, crates/stdio_server/src/session/providers/filer.rs
This PR can reduce the highlighting job on the vim side, sigificantly for the long query string.
Close #628
=> Truncate the tail of long lines

doc/clap.txt
Add more detailed description of NeoVim related `g:clap_enable_background_shadow`.
It's mentioned to #670.
=> :+1: Improve documentation

autoload/clap.vim, doc/clap-support.txt
it's not easy to send query like contain space, '+' etc. Let's use
a command line standard args syntax, all text after '--' is treated
as query instead of opts.
=> accept complex query like command line program

autoload/clap/themes/onehalfdark.vim, autoload/clap/themes/onehalflight.vim
Based on the simple and clean [onehalf themes](https://github.com/sonph/onehalf), I created these for vim-clap. I put some comments specifying which color identifier I used for every Clap element.
=> Added onehalf themes

CHANGELOG.md, autoload/clap/client.vim, autoload/clap/preview.vim, crates/maple_cli/src/stdio_server/mod.rs, crates/maple_cli/src/stdio_server/session/message_handlers/mod.rs, crates/matcher/src/bonus/recent_files.rs
Now users can have an `on_move_async` impl easily for their own providers if the entry is a file path.
```vim 
let g:clap_provider_quick_open = {
\ 'source': ['~/.vimrc', '~/.spacevim', '~/.bashrc', '~/.tmux.conf'],
\ 'sink': 'e',
\ 'on_move_async': { -> clap#client#call_preview_file(v:null) },
\ }
```
=> Add preview/file interface for easier external async preview integration

Makefile, autoload/clap/installer.vim
- `installer.vim` commands spawn a shell on *nix systems to build maple/python
modules. We first ensure vim's `&shell` is set correctly and executable.
Additionally, if we are on BSD system, we call `gmake` instead of make
and pass an enviornment variable to Makefile.
BSD users are informed if they do not have `gmake` installed on their
system.
Resolves #732
=> Resolve invoking Makefiles on FreeBSD/OpenBSD

CHANGELOG.md, crates/filter/src/lib.rs, crates/filter/src/source.rs, crates/maple_cli/benches/benchmark.rs, crates/maple_cli/src/command/ctags/recursive.rs, crates/maple_cli/src/command/exec.rs, crates/maple_cli/src/command/grep.rs, crates/maple_cli/src/process/light.rs, crates/maple_cli/src/process/rstd.rs, crates/maple_cli/src/process/tokio.rs, crates/maple_cli/src/recent_files.rs, crates/maple_cli/src/stdio_server/providers/builtin/mod.rs, crates/maple_cli/src/stdio_server/session/context.rs, crates/maple_cli/src/tools/ctags/mod.rs
The result is 30x faster, test repo: https://github.com/paritytech/substrate
```
parallel recursive ctags
time:   [13.764 ms 13.967 ms 14.164 ms]
change: [-0.4382% +1.6583% +3.7623%] (p = 0.11 > 0.05)
No change in performance detected.
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) low mild
Benchmarking recursive ctags: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 38.9s, or reduce sample count to 10.
recursive ctags         time:   [385.76 ms 387.24 ms 388.80 ms]
change: [+0.4888% +1.1275% +1.7357%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
3 (3.00%) high mild
```
```bash
$ lscpu
Architecture:                    x86_64
CPU op-mode(s): …
```
=> Parallel recursive ctags

autoload/clap/provider/maps.vim
For neovim when running `verbose nmap`
The output maybe either with comments:
e.g.
```
<C-W>R      * <C-W>R<Cmd>ScrollViewRefresh<CR>                                                                                                                         
Last set from ~/.local/share/nvim/site/pack/packer/start/nvim-scrollview/plugin/scrollview.vim line 141
```
Or without comments
```
n  <C-K>       *@<Cmd>lua vim.lsp.buf.signature_help()<CR>                                                                                                                
n  <C-]>       *@<Cmd>lua vim.lsp.buf.definition()<CR>
```
The problem with the current code is that it assumes the mapping is always followed by a line of comment start with `\t`.  And will postpone add to list until a well formatted …
=> Bugfix missing keybindings for neovim

CHANGELOG.md, autoload/clap/provider/filer.vim, crates/icon/src/lib.rs, crates/maple_cli/src/dumb_analyzer/find_usages/mod.rs, crates/maple_cli/src/dumb_analyzer/find_usages/search_engine/ctags/parser.rs, crates/maple_cli/src/dumb_analyzer/find_usages/search_engine/regex/definition.rs, crates/maple_cli/src/dumb_analyzer/find_usages/search_engine/regex/worker.rs, crates/maple_cli/src/stdio_server/deprecated_runner.rs, crates/maple_cli/src/stdio_server/mod.rs, crates/maple_cli/src/stdio_server/providers/builtin/mod.rs, crates/maple_cli/src/stdio_server/providers/builtin/on_move.rs, crates/maple_cli/src/stdio_server/providers/custom/dumb_jump.rs, crates/maple_cli/src/stdio_server/providers/custom/filer.rs, crates/maple_cli/src/stdio_server/providers/custom/recent_files.rs, crates/maple_cli/src/stdio_server/providers/mod.rs, crates/maple_cli/src/stdio_server/rpc/messages/method_call.rs, crates/maple_cli/src/stdio_server/session/manager.rs, crates/maple_cli/src/stdio_server/session/mod.rs, crates/maple_cli/src/stdio_server/session_client.rs, crates/maple_cli/src/utils.rs, crates/types/src/search_term.rs, syntax/clap_grep.vim
Sometimes when we type an initial query and get a bunch of results, we
actually don't want them all and want to exclude some of them, then we continue
typing the inverse search term like `!test`, in which case the results from last query
can be reused and refiltered on, making the dumb_jump provider generally faster.
=> Reuse the last results when it's usable

CHANGELOG.md, autoload/clap/provider/dumb_jump.vim, crates/maple_cli/src/stdio_server/session/mod.rs
=> Introduce debounce on Rust event_loop handling

CHANGELOG.md, README.md, autoload/clap/api.vim, autoload/clap/provider/tags.vim, crates/icon/src/lib.rs, crates/maple_cli/src/command/ctags/mod.rs, crates/maple_cli/src/command/ctags/tagsfile.rs, crates/maple_cli/src/dumb_analyzer/find_usages/search_engine/ctags/mod.rs, crates/maple_cli/src/dumb_analyzer/find_usages/search_engine/mod.rs, crates/maple_cli/src/stdio_server/deprecated_runner.rs, crates/maple_cli/src/stdio_server/providers/builtin/mod.rs, crates/maple_cli/src/stdio_server/session/context.rs, crates/maple_cli/src/stdio_server/session/mod.rs, crates/maple_cli/src/tools/ctags/mod.rs, crates/pattern/src/lib.rs, doc/clap.txt
This PR supports generating the source for `tags` provider using the Rust binary, and remove the `+json` requirement from the ctags executable.
Close #57
=> Remove the vista dep from `tags` provider

CHANGELOG.md, Cargo.lock, crates/maple_cli/src/command/ctags/buffer_tags.rs, crates/maple_cli/src/command/grep/mod.rs, crates/maple_cli/src/dumb_analyzer/find_usages/mod.rs, crates/maple_cli/src/dumb_analyzer/find_usages/search_engine/ctags/mod.rs, crates/maple_cli/src/dumb_analyzer/find_usages/search_engine/gtags/mod.rs, crates/maple_cli/src/dumb_analyzer/find_usages/search_engine/regex/definition.rs, crates/maple_cli/src/dumb_analyzer/find_usages/search_engine/regex/mod.rs, crates/maple_cli/src/dumb_analyzer/find_usages/search_engine/regex/worker.rs, crates/maple_cli/src/dumb_analyzer/mod.rs, crates/maple_cli/src/previewer/mod.rs, crates/maple_cli/src/stdio_server/providers/builtin/mod.rs, crates/maple_cli/src/stdio_server/providers/builtin/on_move.rs, crates/maple_cli/src/stdio_server/providers/custom/dumb_jump/searcher.rs, crates/maple_cli/src/stdio_server/session/context.rs, crates/maple_cli/src/stdio_server/session/mod.rs, crates/maple_cli/src/tools/ripgrep/mod.rs, crates/maple_cli/src/utils.rs, crates/printer/src/truncation.rs, crates/types/src/lib.rs, crates/utility/Cargo.toml, crates/utility/src/lib.rs, pythonx/clap/fuzzymatch-rs/Cargo.lock, src/main.rs
The idea is the same with the nearest function/method symbol provided by vista.vim. The context tag is not guaranteed to be 100% correct.
Close #66
=> preview: show the current method/function when it's invisible

CHANGELOG.md, autoload/clap/maple/command.vim, autoload/clap/provider/grep.vim, crates/maple_cli/src/cache/mod.rs, crates/maple_cli/src/command/cache.rs, crates/maple_cli/src/dumb_analyzer/find_usages/search_engine/ctags/mod.rs, crates/maple_cli/src/dumb_analyzer/find_usages/search_engine/gtags/mod.rs, crates/maple_cli/src/dumb_analyzer/find_usages/search_engine/mod.rs, crates/maple_cli/src/dumb_analyzer/find_usages/search_engine/regex/mod.rs, crates/maple_cli/src/dumb_analyzer/find_usages/search_engine/regex/runner.rs, crates/maple_cli/src/stdio_server/providers/custom/dumb_jump/searcher.rs, crates/maple_cli/src/tools/ripgrep/mod.rs, crates/pattern/src/lib.rs, crates/types/src/search_term.rs, crates/types/src/source_item.rs, doc/clap.txt, syntax/clap_grep.vim
Use a dedicated variable `g:clap_cache_threshold` for the command execution cache threshold instead of binding it to `g:clap_builtin_fuzzy_filter_threshold`.
=> Add clap cache threshold configuration

CHANGELOG.md, Cargo.lock, crates/maple_cli/src/app.rs, crates/upgrade/Cargo.toml, crates/upgrade/src/download.rs, crates/upgrade/src/lib.rs
The number of dependencies also decreased from 293 to 272, which is nice.
Close #846
=> Fix maple upgrade

CHANGELOG.md, autoload/clap/maple/command.vim, crates/icon/src/lib.rs, crates/maple_cli/src/cache/mod.rs, crates/maple_cli/src/command/ctags/buffer_tags.rs, crates/maple_cli/src/command/exec.rs, crates/maple_cli/src/command/grep/forerunner.rs, crates/maple_cli/src/command/grep/mod.rs, crates/maple_cli/src/process/light.rs, crates/maple_cli/src/process/mod.rs, crates/maple_cli/src/process/rstd.rs, crates/maple_cli/src/process/tokio.rs, crates/maple_cli/src/stdio_server/providers/builtin/mod.rs, crates/maple_cli/src/stdio_server/session/mod.rs
It's much more efficient to redirect the output to a file when creating the cache.
```Bash
~/.../plugged/vim-clap ❯❯❯ time ./target/release/maple grep foo --cmd-dir /Users/xuliucheng/src/github.com/subspace/subspace --refresh-cache
Recreating the grep cache for /Users/xuliucheng/src/github.com/subspace/subspace
real    3m31.732s
user    3m35.523s
sys     0m12.804s
~/.../plugged/vim-clap ❯❯❯ time ./target/release/maple grep foo --cmd-dir /Users/xuliucheng/src/github.com/subspace/subspace --refresh-cache
Recreating the grep cache for /Users/xuliucheng/src/github.com/subspace/subspace
real	0m32.364s
user	0m35.097s
sys	0m2.531s
```
=> Redirect command output to file when creating the cache

autoload/clap/provider/buffers.vim
Now the layout is in order from left to right: filename with extension, buffer, file size, icon, current line in buffer, full path, flag and extra.
An example here:
Close #897
=> Improve the window layout of `buffers` provider

autoload/clap/floating_win.vim
Save and restore winminheight in addition to winheight when opening and closing the floating window
=> Save and restore winminheight in addition to winheight

doc/clap.txt
Since https://github.com/liuchengxu/vim-clap/commit/0d630e4aa23315c086e858c1a41ff40e082d0fe7, `clap#navigation#linewise` is unavailable anymore
=> Update document after renaming a function

.github/workflows/ci.yml, autoload/clap/provider/tagfiles.vim, crates/cli/src/command/filter.rs, crates/filter/src/parallel_worker.rs, crates/filter/src/sequential_worker.rs, crates/maple_core/src/dirs.rs, crates/maple_core/src/paths.rs, crates/maple_core/src/searcher/blines.rs, crates/maple_core/src/searcher/files.rs, crates/maple_core/src/searcher/mod.rs, crates/maple_core/src/searcher/tagfiles.rs, crates/maple_core/src/stdio_server/handler/on_initialize.rs, crates/maple_core/src/stdio_server/provider/filer.rs, crates/maple_core/src/stdio_server/provider/generic_provider.rs, crates/maple_core/src/stdio_server/provider/mod.rs, crates/maple_core/src/stdio_server/provider/recent_files.rs, crates/maple_core/src/stdio_server/provider/tagfiles.rs, crates/printer/src/lib.rs, syntax/clap_tagfiles.vim
This PR implements a new provider `tagfiles` which reads the `tags` file from `cwd`, a continuation of the work from #557 (Thanks to @romgrk!). The architecture has been heavily reworked, it's now much easier to integrate it. There are some obvious room for improvement, I have marked TODOs there, please go ahead if anyone is interested in fixing them.
Close #446
=> Add tagfiles provider

crates/icon/Cargo.toml, crates/upgrade/src/lib.rs, install.sh
Replace `cut` with `awk` in `install.sh`.
Resolves #946
Resolves #947
=> Eliminate `cut` usage from install.sh

README.md, ftplugin/clap_input.vim, syntax/clap_files.vim
=> Improve syntax highlight of clap files

autoload/clap.vim, autoload/clap/floating_win.vim, autoload/clap/state.vim, autoload/clap/themes.vim, crates/maple_core/src/config.rs, crates/maple_core/src/previewer/mod.rs, crates/maple_core/src/stdio_server/handler/on_move.rs, crates/maple_core/src/stdio_server/provider/dumb_jump/searcher.rs, crates/maple_core/src/stdio_server/provider/mod.rs, doc/clap.txt
When the preview direction is `LR` for neovim, the scrollbar will be enabled automatically. If you'd like to customize the scrollbar or disable it,
```vim
" Change the fill char of scrollbar
let g:clap_preview = { 'scrollbar': { 'fill_char': '▌' } }
" Disable the scrollbar
let g:clap_preview = { 'scrollbar': { 'fill_char': '' } }
```
=> Initiall support of preview scrollbar for neovim

crates/maple_core/src/stdio_server/provider/files.rs
```
:Clap files --path /etc/ --no-cwd
```
And if I choose anything, it results in an error.
```
vim-clap: target_dir:['/etc/'], Run:function('42', {'is_sync': function('57'), 'init_display_win': function('59'), 'supp
ort_multi_select': function('52'), '_apply_sink': function('42'), 'id': 'files', 'filter': function('51'), 'sink_star': 
function('45'), 'sink': function('44'), 'support_open_action': function('53'), '_': function('40'), 'is_pure_async': fun
ction('58'), 'try_set_syntax': function('55'), 'on_typed': function('47'), 'on_exit': function('49'), 'has_enable_rooter
': function('43'), 'jobstop': function('50'), 'abort': function('41'), 'is_rpc_type': function('54'), 'on_enter': functi
on('46'), '_apply_source': function('56'), 'on_move': function('48')}), run_args:'rpc', …
```
=> `:Clap files --path foo --no-cwd` fails

Cargo.lock, autoload/clap/plugin/git.vim, autoload/clap/plugin/linter.vim, crates/Cargo.toml, crates/linter/Cargo.toml, crates/linter/src/lib.rs, crates/linter/src/linters/go.rs, crates/linter/src/linters/rust.rs, crates/linter/src/linters/sh.rs, crates/linter/src/linters/typos.rs, crates/linter/src/linters/vim.rs, crates/maple_core/src/stdio_server/plugin/linter.rs, crates/maple_core/src/stdio_server/service.rs
This PR brings a number of improvements to the linter plugin, mostly UI-related.
- Support multiple spans for a single diagnostic, especially useful for Rust.
- Show the exact diagnostic when the cursor is right in the corresponding span, otherwise, if the cursor is not in any of the range of diagnostics in this line, show all the diagnostics in this line.
- Add icon to diagnostic severity.
- Make sure the diagnostic window on the top right won't interfere with the regular source code display.
=> Refine linter plugin

Cargo.lock, Cargo.toml, autoload/clap/helper.vim, autoload/clap/highlighter.vim, autoload/clap/provider/providers.vim, autoload/clap/state.vim, crates/maple_core/src/config.rs, crates/maple_core/src/stdio_server/mod.rs, crates/maple_core/src/stdio_server/plugin/markdown.rs, crates/maple_core/src/stdio_server/plugin/mod.rs, crates/maple_core/src/stdio_server/plugin/syntax.rs, crates/maple_core/src/stdio_server/plugin/system.rs, crates/maple_core/src/stdio_server/provider/hooks/on_move.rs, crates/maple_core/src/tools/ctags/mod.rs, crates/maple_derive/src/impls/clap_plugin.rs, crates/printer/src/lib.rs, crates/sublime_syntax/src/lib.rs, crates/tree_sitter/Cargo.toml, crates/tree_sitter/src/language.rs, docs/src/plugins/intro.md, docs/src/plugins/plugins.md, plugin/clap.vim, rust-toolchain.toml, src/main.rs
Close #532
Add the following config in `config.toml` to enable the tree-sitter highlight:
```
[provider]
preview-highlight-engine = "tree-sitter"
```
=> Support tree-sitter highlight for provider preview

autoload/clap/layout.vim
I fixed extending `layout` with `g:clap_layout`.
=> Fix `g:clap_layout` is not applied in v0.49

CHANGELOG.md, crates/maple_core/src/searcher/file.rs, crates/maple_core/src/searcher/files.rs, crates/maple_core/src/searcher/grep/mod.rs, crates/maple_core/src/searcher/grep/stoppable_searcher.rs, crates/maple_core/src/searcher/mod.rs, crates/maple_core/src/searcher/tagfiles.rs
This PR optimize the searcher performance even further, the hyperfine result indicates it's significantly improved by 60%. The series of optimization efforts have achieved 2x performance than v0.52.
```
hyperfine --warmup 3 './maple-v0.52 grep --ripgrep --cmd-dir /home/xlc/Data2/github.com/paritytech/polkadot-sdk/ client'  './maple-master grep --lib-ripgrep --cmd-dir /home/xlc/Data2/github.com/paritytech/polkadot-sdk/ client' './target/release/maple grep --lib-ripgrep --cmd-dir /home/xlc/Data2/github.com/paritytech/polkadot-sdk/ client'
Benchmark 1: ./maple-v0.52 grep --ripgrep --cmd-dir /home/xlc/Data2/github.com/paritytech/polkadot-sdk/ client
Time (mean ± σ):     657.0 ms ±  19.9 ms    [User: 1242.2 ms, System: 461.2 ms]
Range (min … max):   610.5 ms … 677.2 ms    10 runs
Benchmark 2: …
```
=> Optimize searcher performance significantly

Cargo.lock, crates/cli/src/command/grep/mod.rs, crates/maple/Cargo.toml, crates/maple/src/main.rs, crates/maple_core/src/searcher/grep/mod.rs, crates/maple_core/src/searcher/grep/stoppable_searcher.rs, crates/maple_core/src/searcher/mod.rs, crates/matcher/Cargo.toml, crates/matcher/src/algo/fzf.rs, crates/matcher/src/algo/mod.rs, crates/matcher/src/algo/nucleo.rs, crates/types/src/matcher.rs
When the query is merely one or two chars, the tokio mpsc channel could be heavily used which can be one bottleneck as we observed before. This PR optimizes for this scenario, ~20% boost gained, the impact of this tactic on the performance of other cases is negligible.
```
hyperfine --warmup 3 -L query c './maple-master grep --lib-ripgrep --cmd-dir /home/xlc/Data2/github.com/paritytech/polkadot-sdk/ {query}' './target/release/maple grep --lib-ripgrep --cmd-dir /home/xlc/Data2/github.com/paritytech/polkadot-sdk/ {query}'
Benchmark 1: ./maple-master grep --lib-ripgrep --cmd-dir /home/xlc/Data2/github.com/paritytech/polkadot-sdk/ c
Time (mean ± σ):     616.3 ms ±  12.6 ms    [User: 1011.6 ms, System: 530.5 ms]
Range (min … max):   590.6 ms … 629.2 ms    10 runs
Benchmark 2: …
```
=> Optimize grep performance specifically for short queries

autoload/clap.vim, autoload/clap/api/clap.vim
Hi @liuchengxu,
I am adding PR to update variable name from `Source` to `ClapProviderSource` to avoid function name conflict. In my case, I have a `Source` function to source vim config. I can change my config to fix this issue but I think that `Source` is quite common function name, others can be affected by this error as well. Please help me to review and accept this PR if you find it does make senses, thanks.
```
Error detected while processing function clap#[45]..clap#open_provider[23]..<SNR>45_detect_source_type:
line    1:
E705: Variable name conflicts with existing function: Source
```
=> Update variable name for source to avoid function name conflict
