README.md
autoload/clap.vim
autoload/clap/dispatcher.vim
autoload/clap/filter.vim
autoload/clap/floating_win.vim
autoload/clap/impl.vim
autoload/clap/init.vim
autoload/clap/popup.vim
autoload/clap/provider/grep.vim
syntax/clap_blines.vim
syntax/clap_command_history.vim
syntax/clap_grep.vim

Handling the job control in vim-clap makes it easier to create a new async provider: just preparing the cmd for the job and taking care of the whole workflow.

Split out dispatcher.vim

---

.github/workflows/ci.yml
.gitignore
.travis.yml
README.md
autoload/clap/floating_win.vim
autoload/clap/init.vim
autoload/clap/popup.vim

- Close #9
- Also fix init_hi_group(), partially related to #10

Disable completeopt by default

---

README.md
autoload/clap/api.vim
autoload/clap/dispatcher.vim
autoload/clap/floating_win.vim
autoload/clap/handler.vim
autoload/clap/impl.vim
autoload/clap/init.vim
autoload/clap/sign.vim

Refine current selection sign

---

README.md
autoload/clap/api.vim
autoload/clap/dispatcher.vim
autoload/clap/floating_win.vim
autoload/clap/popup.vim
ftplugin/clap_input.vim

Support CTRL-D

---

README.md
autoload/clap/api.vim
autoload/clap/provider/files.vim
autoload/clap/provider/grep.vim
autoload/clap/util.vim

Add enable_rooter flag for proviers

---

README.md
autoload/clap/dispatcher.vim
autoload/clap/impl.vim
autoload/clap/sign.vim
doc/clap.txt

Also ensure the sign of first line is not empty

Don't ignore the error when dispatching the job

---

autoload/clap/api.vim
autoload/clap/dispatcher.vim
autoload/clap/filter.vim
autoload/clap/provider/grep.vim
doc/clap.txt

Also improve the default async calling time.
- Close #62
- Improve #61

Allow disabling the icon drawing in Clap grep

---

CHANGELOG.md
README.md
autoload/clap/api.vim
autoload/clap/dispatcher.vim
autoload/clap/impl.vim
autoload/clap/sign.vim
autoload/clap/util.vim
doc/clap.txt

Rename sign and rooter related options

---

README.md
autoload/clap/provider/history.vim
autoload/clap/util.vim
doc/clap.txt
plugin/clap.vim

Add history provider

---

CHANGELOG.md
autoload/clap/api.vim
autoload/clap/icon.vim
autoload/clap/provider/buffers.vim
autoload/clap/util.vim
syntax/clap_buffers.vim

Rework buffers provider

---

CHANGELOG.md
README.md
autoload/clap.vim
autoload/clap/api.vim
autoload/clap/floating_win.vim
autoload/clap/impl.vim
autoload/clap/init.vim
autoload/clap/popup.vim
autoload/clap/provider/files.vim
autoload/clap/util.vim
doc/clap.txt

Formalize context args

---

autoload/clap.vim

This simple implementation for invoking clap with selected clap provider works for me --- but any feedback or corner case would be appreciated!

Implement sink for the default (underscore) provider

---

README.md
autoload/clap/provider/yanks.vim
doc/clap.txt
plugin/clap.vim

Add yanks provider
This is largely based on https://github.com/sgur/ctrlp-extensions.vim
This should address #76 
I am new to vim scripting. Suggestions are welcome!

[RFC]Add yanks provider

---

autoload/clap/api.vim
autoload/clap/filter.vim
autoload/clap/impl.vim
autoload/clap/indicator.vim
autoload/clap/init.vim
autoload/clap/popup.vim
autoload/clap/provider/files.vim
autoload/clap/provider/filetypes.vim
autoload/clap/provider/git_files.vim
autoload/clap/provider/jumps.vim
autoload/clap/provider/yanks.vim
autoload/clap/util.vim
doc/clap.txt

Define ClapFuzzyMatches* hl groups

---

CHANGELOG.md
README.md
autoload/clap/provider/marks.vim
doc/clap.txt
plugin/clap.vim

Refine doc

---

autoload/clap/dispatcher.vim
autoload/clap/impl.vim

Use job's cwd option

---

autoload/clap.vim
autoload/clap/api.vim
doc/clap.txt
syntax/clap_global.vim

Use the Description comment line of soure file as about

---

CHANGELOG.md
autoload/clap.vim
autoload/clap/provider/command_history.vim

Apply sink on_exit for command_history provider

---

.gitignore
CHANGELOG.md
README.md
autoload/clap.vim
autoload/clap/api.vim
autoload/clap/dispatcher.vim
autoload/clap/filter.vim
autoload/clap/forerunner.vim
autoload/clap/handler.vim
autoload/clap/impl.vim
autoload/clap/job.vim
autoload/clap/provider/files.vim
autoload/clap/provider/grep.vim
autoload/clap/util.vim
doc/clap.txt
plugin/clap.vim
syntax/clap_grep.vim

Allow running from any directory for the files and grep provider

---

autoload/clap.vim
autoload/clap/impl.vim

Fixes https://github.com/liuchengxu/vim-clap/issues/128#issuecomment-555507604

Try caching the raw sync provider source

---

autoload/clap/icon.vim
autoload/clap/impl.vim
autoload/clap/init.vim
autoload/clap/popup.vim
syntax/clap_grep.vim

Fix the unexpected background color of the icons.

Improve icon highlight

---

autoload/clap/api.vim
autoload/clap/filter.vim
autoload/clap/provider/files.vim
autoload/clap/provider/grep.vim
autoload/clap/rooter.vim

Use absolute directory for g:__clap_provider_cwd

---

autoload/clap/api.vim

Fix pressing C-J/K without input causes an error.

---

autoload/clap/filter.vim
autoload/clap/impl.vim
pythonx/clap/fzy.py

Refactoring for Rust extension

---

autoload/clap/filter.vim
autoload/clap/impl.vim
pythonx/clap/fzy.py

Reverts liuchengxu/vim-clap#148

Revert "Refactoring for Rust extension"

---

.gitignore
CHANGELOG.md
autoload/clap/filter.vim
autoload/clap/provider/grep.vim
pythonx/clap/fzy.py

Add limited search syntax for grep provider

---

README.md
autoload/clap/provider/git_diff_files.vim
doc/clap.txt

Provider for files which is managed by git and have uncommitted changes.

Add git_diff_files provider

---

autoload/clap/api.vim
autoload/clap/filter.vim
autoload/clap/forerunner.vim
autoload/clap/impl.vim
doc/clap.txt
test/README.md
test/profile.vimrc
test/run-profile.sh
test/test_fuzzy_filter.vim

Used for comparing the Rust extension introduced in #147.

Add basic performance profile

---

Makefile
autoload/clap/helper.vim

Running two `term`s seems to not work well.

Fix clap#helper#build_all()

---

README.md
autoload/clap/provider/quickfix.vim
doc/clap.txt

Quickfix provider

---

.github/workflows/ci.yml
CHANGELOG.md
autoload/clap/helper.vim
pythonx/clap/fuzzymatch-rs/Cargo.toml
pythonx/clap/fuzzymatch-rs/rust-toolchain
pythonx/clap/fuzzymatch-rs/src/lib.rs
pythonx/clap/scorer.py

Add subscorer for Rust extension

---

autoload/clap/dispatcher.vim
autoload/clap/forerunner.vim
autoload/clap/impl.vim
autoload/clap/maple.vim
src/main.rs

Fix default async job impl flicker

---

Cargo.lock
Cargo.toml
README.md
autoload/clap/forerunner.vim
autoload/clap/impl.vim
autoload/clap/maple.vim
autoload/clap/provider/files.vim
pythonx/clap/extracted_fzy/Cargo.lock
pythonx/clap/fuzzymatch-rs/Cargo.toml
src/icon.rs
src/main.rs
syntax/clap_files.vim

Add icon for files provider

---

autoload/clap/filter.vim

Use safer absolute path for importing pythonx/clap

---

CHANGELOG.md
autoload/clap.vim
autoload/clap/api.vim
autoload/clap/impl.vim

In case of you somehow open vim-clap with 1 million lines.

Optimize for blines provider

---

autoload/clap/provider/buffers.vim

Fix buffers provider error when :buffers is empty

---

CHANGELOG.md
autoload/clap/forerunner.vim
autoload/clap/impl.vim
autoload/clap/maple.vim
autoload/clap/provider/files.vim
autoload/clap/provider/git_files.vim
src/main.rs

Support running piped command in maple

---

.github/workflows/release.yml
CHANGELOG.md
INSTALL.md
README.md
autoload/clap.vim
autoload/clap/helper.vim
install.ps1
install.sh

Install the prebuilt binary automatically

---

autoload/clap/floating_win.vim

Check if the buf for floating_win is still valid

---

CHANGELOG.md
autoload/clap/provider/blines.vim

Push the current position to the jumplist when applying blines sink

---

CHANGELOG.md
README.md
autoload/clap/provider/location_list.vim
autoload/clap/provider/loclist.vim
autoload/clap/provider/quickfix.vim
doc/clap.txt

Add location list provider

---

CHANGELOG.md
autoload/clap/api.vim
autoload/clap/filter.vim
autoload/clap/filter/viml.vim

Vim9 is already getting started in the vim code base. This refactor is for the potential future vim9 improvement.

Split out filter native viml impl

---

CHANGELOG.md
autoload/clap/floating_win.vim
autoload/clap/indicator.vim
autoload/clap/popup.vim
autoload/clap/spinner.vim
doc/clap.txt

Introduce g:ClapPrompt for more control of prompt

---

autoload/clap.vim
autoload/clap/common_history.vim
autoload/clap/provider/command_history.vim
autoload/clap/provider/search_history.vim
doc/clap-support.txt

I just add a search history support, it copied from command_history.vim.

Add search history provider

---

autoload/clap/provider/maps.vim
doc/clap-support.txt

Add maps provider to list key mappings

---

CHANGELOG.md
README.md
autoload/clap/job.vim
autoload/clap/path.vim
autoload/clap/provider/commits.vim
autoload/clap/rooter.vim
doc/clap.txt

Add g:clap_project_root_markers

---

CHANGELOG.md
autoload/clap/ext.vim
autoload/clap/preview.vim
autoload/clap/provider/blines.vim
autoload/clap/provider/files.vim
autoload/clap/provider/git_files.vim
autoload/clap/provider/grep.vim
autoload/clap/provider/history.vim
autoload/clap/provider/marks.vim
autoload/clap/provider/tags.vim
autoload/clap/themes.vim
autoload/clap/themes/material_design_dark.vim
autoload/clap/util.vim

Add preview for files and history provider

---

CHANGELOG.md
README.md
autoload/clap/preview.vim
autoload/clap/provider/blines.vim
autoload/clap/provider/buffers.vim
autoload/clap/provider/yanks.vim
autoload/clap/util.vim
doc/clap.txt

Add preview support for yanks and buffers provider

---

CHANGELOG.md
autoload/clap.vim
autoload/clap/util.vim
doc/clap.txt
ftplugin/clap_input.vim

Add g:clap_insert_mode_only for disabling the other mode feature

---

CHANGELOG.md
README.md
autoload/clap.vim
autoload/clap/util.vim
plugin/clap.vim

Add visual selection support for Clap command

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
autoload/clap.vim
autoload/clap/api.vim
autoload/clap/filter/async/dyn.vim
autoload/clap/floating_win.vim
autoload/clap/forerunner.vim
autoload/clap/handler.vim
autoload/clap/impl.vim
autoload/clap/job/stdio.vim
autoload/clap/maple.vim
autoload/clap/provider/grep.vim
autoload/clap/state.vim
crates/fuzzy_filter/src/lib.rs
crates/maple_cli/src/cmd/cache.rs
crates/maple_cli/src/cmd/filter/dynamic.rs
crates/maple_cli/src/cmd/grep.rs
crates/maple_cli/src/cmd/mod.rs
crates/maple_cli/src/cmd/rpc/filer.rs
crates/maple_cli/src/light_command.rs
crates/maple_cli/src/utils.rs
src/main.rs
syntax/clap_grep.vim

Add new grep2 provider with cache and dynamic refresh support

---

autoload/clap/icon.vim
crates/icon/extension_map.json
crates/icon/src/constants.rs
crates/icon/src/lib.rs
crates/maple_cli/src/light_command.rs

New icon/emoji should be one unicode char, 3 bytes. Ref #392

Each icon with one extra space should be 4 bytes

---

README.md
ftplugin/clap_input.vim

Press ESC twice to close Clap window

---

CHANGELOG.md
Cargo.lock
README.md
autoload/clap/filter/async/dyn.vim
autoload/clap/maple.vim
autoload/clap/preview.vim
autoload/clap/provider/grep.vim
autoload/clap/provider/proj_tags.vim
autoload/clap/provider/tags.vim
autoload/clap/sink.vim
crates/fuzzy_filter/src/content_filtering.rs
crates/fuzzy_filter/src/lib.rs
crates/maple_cli/Cargo.toml
crates/maple_cli/src/cmd/cache.rs
crates/maple_cli/src/cmd/filter/mod.rs
crates/maple_cli/src/cmd/grep.rs
crates/maple_cli/src/cmd/mod.rs
crates/maple_cli/src/cmd/tags.rs
doc/clap-support.txt
src/main.rs
syntax/clap_proj_tags.vim
syntax/clap_tags.vim

Add proj_tags provider

---

autoload/clap/themes/solarized_dark.vim
autoload/clap/themes/solarized_light.vim
doc/clap.txt

Add Solarized themes

---

autoload/clap/themes/nord.vim

Add Nord theme

---

CHANGELOG.md
autoload/clap.vim
autoload/clap/impl/on_move.vim
autoload/clap/preview.vim
autoload/clap/provider/blines.vim
autoload/clap/provider/buffers.vim
autoload/clap/provider/grep.vim
autoload/clap/provider/marks.vim
autoload/clap/provider/tags.vim
doc/clap.txt

Add `g:clap_preview_size` for customizing the number of preview lines.
Close #424

Clap preview size

---

CHANGELOG.md
autoload/clap/provider/buffers.vim
autoload/clap/provider/history.vim
autoload/clap/util.vim
doc/clap.txt
plugin/clap.vim

Add g:clap_provider_buffers_cur_tab_only

---

CHANGELOG.md
README.md
autoload/clap/provider/yanks.vim
doc/clap.txt

Persistent yanks

---

CHANGELOG.md
autoload/clap.vim
doc/clap.txt

Add clap#run()

---

CHANGELOG.md
INSTALL.md
autoload/clap/installer.vim
crates/matcher/src/algo.rs
crates/stdio_server/src/filer.rs
pythonx/clap/fuzzymatch-rs/Cargo.lock
pythonx/clap/fuzzymatch-rs/Cargo.toml
pythonx/clap/fuzzymatch-rs/rust-toolchain
pythonx/clap/fuzzymatch-rs/src/lib.rs

pyo3 supports stable Rust since 0.11

---

autoload/clap/provider/bcommits.vim
autoload/clap/provider/commits.vim
syntax/clap_diff.vim

Allow bcommits and commits to preview the changes (git log and git show)

Provider preview for git commits and bcommits

---

CHANGELOG.md
autoload/clap/provider/filer.vim
autoload/clap/rooter.vim

Fix current file name expand matching

---

.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
Dockerfile
ci/build_static_binary.sh
crates/upgrade/src/github.rs
install.sh

Build static binary via GA

---

CHANGELOG.md
autoload/clap/selection.vim

Support open action for multiple selections

---

PROVIDER.md
autoload/clap/popup/move_manager.vim
autoload/clap/provider/filer.vim

Change the signature of `bs_action` for Vim

---

CHANGELOG.md
autoload/clap/client.vim
autoload/clap/impl/on_move.vim
autoload/clap/provider/commits.vim
autoload/clap/provider/filer.vim
autoload/clap/sign.vim
crates/stdio_server/src/filer.rs

- Also fix an unwrap in Rust.
Close #500
Close #501

Let the callback also handle the error itself

---

autoload/clap/installer.vim

Resolve file locking while updating binaries

---

CHANGELOG.md
autoload/clap/client.vim
crates/matcher/extracted_fzy/src/lib.rs
crates/stdio_server/src/session/handler/on_move.rs

Truncate the insanely long preview lines

---

autoload/clap/handler.vim
ftplugin/clap_input.vim

Don't use stopinsert inside the handler

---

autoload/clap/provider/filer.vim
syntax/clap_filer.vim

Closes #571 
- feat: make filer prompt relative to cwd or user home
- fix: filer input cleared on back_action
- feat: improve create-new-file entry
- didn't add the keybinding to switch between files & filer because I'm too lazy

Improve filer ui

---

autoload/clap/provider/filer.vim

Fix: filer

---

autoload/clap/floating_win.vim
autoload/clap/popup.vim
autoload/clap/themes.vim
autoload/clap/themes/material_design_dark.vim
autoload/clap/themes/solarized_light.vim

There doesn't seem to be a way to customize the indicator window text currently.

feat: add ClapIndicator for the indicator window

---

CHANGELOG.md
autoload/clap/filter.vim
doc/clap.txt

Support the builtin matchfuzzy()

---

CHANGELOG.md
autoload/clap/provider/history.vim
doc/clap.txt

Add g:ClapProviderHistoryFilter for configuring the history source

---

autoload/clap/filter.vim

the problem may introduced by https://github.com/liuchengxu/vim-clap/commit/d8163a6b69f3b2db718f6a03f6cfa72f05be9a56

fix: fixup lua can not be used when available

---

CHANGELOG.md
autoload/clap/provider/filer.vim
lua/fzy_filter.lua

Show create new file entry when in empty directory

---

.github/workflows/ci.yml
CHANGELOG.md
autoload/clap/filter.vim
autoload/clap/filter/sync/python.vim
crates/matcher/src/lib.rs
crates/source_item/src/lib.rs
pythonx/clap/fuzzymatch-rs/src/lib.rs
pythonx/clap/fzy.py

I'm going to add more heuristic bonus strategies for the matcher and that requires
more context info, this refactoring will make input more context easier.
Users need to recompile the Python dynamic module for this update.

Introduce MatchText

---

CHANGELOG.md
autoload/clap.vim
autoload/clap/api.vim
autoload/clap/filter.vim
autoload/clap/floating_win.vim
autoload/clap/impl/on_move.vim
autoload/clap/layout.vim
autoload/clap/popup.vim
autoload/clap/preview.vim
doc/clap.txt

Set g:clap_open_preview = 'never' to disable the preview window

---

CHANGELOG.md
autoload/clap/client.vim
autoload/clap/impl/on_move.vim
autoload/clap/provider/grep.vim
crates/stdio_server/src/types.rs

Pass g:clap_provider_grep_enable_icon to Rust end

---

CHANGELOG.md
crates/matcher/src/algo.rs
pythonx/clap/scorer.py

Support unordered substring query

---

CHANGELOG.md
autoload/clap/action.vim
autoload/clap/floating_win/action.vim
ftplugin/clap_action.vim

Close #478
Press `Enter` on the item to apply the selection.

Support floating_win based action menu

---

autoload/clap/client.vim
autoload/clap/ext.vim
autoload/clap/job/daemon.vim
crates/stdio_server/src/ext.rs
crates/stdio_server/src/lib.rs
crates/stdio_server/src/types.rs

To save 0.1s when initializing the ext map :(.

Initialize file extention to filetype map on Rust side

---

Cargo.lock
Cargo.toml
crates/maple_cli/Cargo.toml
crates/maple_cli/src/app.rs
crates/maple_cli/src/cmd/cache.rs
crates/maple_cli/src/cmd/dumb_jump.rs
crates/maple_cli/src/cmd/exec.rs
crates/maple_cli/src/cmd/filter.rs
crates/maple_cli/src/cmd/grep.rs
crates/maple_cli/src/cmd/tags.rs
crates/maple_cli/src/lib.rs
crates/maple_cli/src/process/light.rs
crates/maple_cli/src/process/mod.rs
crates/maple_cli/src/process/std.rs
crates/maple_cli/src/process/tokio.rs
crates/maple_cli/src/stdio_server/mod.rs
crates/maple_cli/src/stdio_server/session/event_handlers/on_init.rs
crates/maple_cli/src/stdio_server/session/providers/dumb_jump.rs
crates/maple_cli/src/tools/rg.rs
crates/upgrade/src/download.rs
crates/upgrade/src/lib.rs
crates/utility/src/lib.rs
src/main.rs

```bash
$ time ./maple-sync dumb-jump Applyable rs --cmd-dir /home/xlc/src/github.com/paritytech/substrate
real	0m0.062s
user	0m0.335s
sys	0m0.047s
$ time ./maple-async dumb-jump Applyable rs --cmd-dir /home/xlc/src/github.com/paritytech/substrate
real	0m0.032s
user	0m0.364s
sys	0m0.076s
```

Asyncify Rust CLI

---

autoload/clap/preview.vim
autoload/clap/provider/quickfix.vim
crates/maple_cli/src/process/mod.rs
crates/maple_cli/src/stdio_server/mod.rs
crates/maple_cli/src/stdio_server/previewer.rs
crates/maple_cli/src/stdio_server/previewer/mod.rs
crates/maple_cli/src/stdio_server/previewer/vim_help.rs
crates/maple_cli/src/stdio_server/session/context.rs
crates/maple_cli/src/stdio_server/session/event_handlers/on_move.rs
crates/maple_cli/src/stdio_server/session/message_handlers/mod.rs
crates/maple_cli/src/stdio_server/session/mod.rs
crates/maple_cli/src/stdio_server/session/providers/filer.rs
crates/maple_cli/src/stdio_server/session/providers/mod.rs
crates/maple_cli/src/stdio_server/session/providers/quickfix.rs
crates/maple_cli/src/stdio_server/types.rs

Impl quickfix preview

---

CHANGELOG.md
autoload/clap.vim
autoload/clap/floating_win.vim
autoload/clap/layout.vim
autoload/clap/popup.vim

Make indicator winwidth more flexible

---

CHANGELOG.md
autoload/clap/api.vim
autoload/clap/provider/grep.vim
crates/source_item/src/lib.rs

Fix the icon offset in truncated grep line

---

CHANGELOG.md
autoload/clap/filter.vim
autoload/clap/handler.vim
autoload/clap/job/regular/maple.vim
autoload/clap/rooter.vim
autoload/clap/state.vim
crates/maple_cli/src/commands/grep.rs

Fixes #711
Also fixes the sink when no results found.
Close #533

Push `.` to the end for all platforms

---

autoload/clap/maple/command.vim
autoload/clap/provider/proj_tags.vim
crates/maple_cli/src/app.rs
crates/maple_cli/src/command/blines.rs
crates/maple_cli/src/command/ctags.rs
crates/maple_cli/src/command/ctags/mod.rs
crates/maple_cli/src/command/ctags/recursive.rs
crates/maple_cli/src/command/ctags/tagsfile.rs
crates/maple_cli/src/command/dumb_jump.rs
crates/maple_cli/src/command/exec.rs
crates/maple_cli/src/command/filter.rs
crates/maple_cli/src/command/grep.rs
crates/maple_cli/src/command/helptags.rs
crates/maple_cli/src/command/mod.rs
crates/maple_cli/src/lib.rs
crates/maple_cli/src/paths.rs
crates/maple_cli/src/tools/ctags.rs

The future plan is to support some features of https://github.com/universal-ctags/citre in vim-clap.

Refactor tags command

---

CHANGELOG.md
Cargo.lock
crates/filter/src/lib.rs
crates/maple_cli/src/recent_files.rs
crates/maple_cli/src/stdio_server/event_handlers/mod.rs
crates/maple_cli/src/stdio_server/providers/dumb_jump.rs
crates/maple_cli/src/stdio_server/providers/filer.rs
crates/maple_cli/src/stdio_server/providers/recent_files.rs
crates/maple_cli/src/stdio_server/session/mod.rs
crates/matcher/Cargo.toml
crates/matcher/src/bonus/cwd.rs
crates/matcher/src/bonus/filename.rs
crates/matcher/src/bonus/mod.rs
crates/matcher/src/lib.rs
pythonx/clap/fuzzymatch-rs/Cargo.lock

Add a bonus score for the `recent_files` entry if it matches the current working directory.

Add a bonus score for each entry of `recent_files` based on cwd

---

CHANGELOG.md
autoload/clap/client.vim
autoload/clap/ext.vim
autoload/clap/job/daemon.vim
crates/icon/src/lib.rs
crates/maple_cli/Cargo.toml
crates/maple_cli/benches/benchmark.rs
crates/maple_cli/src/command/dumb_jump.rs
crates/maple_cli/src/command/grep.rs
crates/maple_cli/src/dumb_analyzer/search_based/definition.rs
crates/maple_cli/src/dumb_analyzer/search_based/runner.rs
crates/maple_cli/src/process/mod.rs
crates/maple_cli/src/process/rstd.rs
crates/maple_cli/src/process/tokio.rs
crates/maple_cli/src/stdio_server/message_handlers/mod.rs
crates/maple_cli/src/stdio_server/providers/builtin/mod.rs
crates/maple_cli/src/stdio_server/providers/custom/dumb_jump.rs
crates/maple_cli/src/stdio_server/providers/custom/filer.rs
crates/maple_cli/src/stdio_server/providers/custom/quickfix.rs
crates/maple_cli/src/stdio_server/providers/custom/recent_files.rs
crates/maple_cli/src/stdio_server/session/mod.rs

Based on the benchmark, the performance using rayon is always better than the plain version, ranging from 1 thousand to 1 million items.

Improve the performance on top of rayon

---

autoload/clap.vim
autoload/clap/floating_win.vim
autoload/clap/layout.vim
autoload/clap/popup.vim
autoload/clap/preview.vim
doc/clap.txt

resolves https://github.com/liuchengxu/vim-clap/issues/766

`g:clap_preview_direction = 'AUTO'` option

---

CHANGELOG.md
autoload/clap/impl/on_typed.vim
autoload/clap/job/stdio.vim
autoload/clap/maple/command.vim
autoload/clap/provider/blines.vim
crates/filter/src/dynamic.rs
crates/filter/src/lib.rs
crates/maple_cli/src/app.rs
crates/maple_cli/src/command/blines.rs
crates/maple_cli/src/command/ctags/recursive_tags.rs
crates/maple_cli/src/command/filter.rs
crates/maple_cli/src/command/grep/mod.rs
crates/maple_cli/src/stdio_server/providers/builtin/mod.rs
crates/maple_cli/src/utils.rs
crates/matcher/extracted_fzy/src/lib.rs
crates/matcher/src/algo/fzy.rs
crates/matcher/src/algo/mod.rs
crates/matcher/src/algo/skim.rs
crates/matcher/src/algo/substring.rs
crates/matcher/src/lib.rs
crates/types/src/lib.rs
crates/types/src/source_item.rs
doc/clap.txt
pythonx/clap/fuzzymatch-rs/src/lib.rs

For example, `:Clap files +ignorecase`.
Close #784

Introduce case-insensitive search option `+ignorecase`

---

.github/workflows/ci.yml
CHANGELOG.md
autoload/clap/provider/filer.vim

Escape the file name for filer provider

---

CHANGELOG.md
autoload/clap/provider/tags.vim

Seperate the vista impl for tags provider completely

---

autoload/clap/api.vim
autoload/clap/job/regular/forerunner.vim
autoload/clap/job/regular/maple.vim
autoload/clap/selection.vim
autoload/clap/state.vim
crates/maple_cli/src/process/light.rs
crates/maple_cli/src/stdio_server/providers/builtin/mod.rs
crates/maple_cli/src/stdio_server/providers/custom/recent_files.rs
crates/printer/src/lib.rs

Signal if the icon is added to the head of line instead of gussing

---

Cargo.lock
crates/matcher/Cargo.toml
crates/pattern/Cargo.toml
crates/pattern/src/lib.rs
crates/utility/Cargo.toml
crates/utility/src/io.rs
crates/utility/src/lib.rs
pythonx/clap/fuzzymatch-rs/Cargo.lock
pythonx/clap/fuzzymatch-rs/Cargo.toml
pythonx/clap/fuzzymatch-rs/src/lib.rs

Simplify fuzzymatch-rs dependencies

---

autoload/clap/installer.vim

A proposal to workaround bug #846.
When using the pre-built binary:
- When maple fails to self-update, attempts to download the updated release directly instead.
Notes:
- Made a callback to call from s:OnExit which is called when a:status indicates a failure. In the case of maple self-update failure it then tries to download directly.
- Had to move s:OnExit closure to outer script scope, because the nested call to s:run_term couldn't redefine s:OnExit closure while in use.
- This is a workaround for the problem, the bug in the maple self-update could be fixed too or instead.

Workaround v0.34->v0.35 maple self-update failure

---

.github/workflows/release.yml
CHANGELOG.md
Cargo.lock
crates/upgrade/Cargo.toml
crates/upgrade/src/github.rs
crates/upgrade/src/lib.rs

Build more executables using cross-compile

---

crates/cli/src/command/filter.rs
crates/filter/src/parallel_worker.rs
crates/filter/src/sequential_worker.rs
crates/maple_core/src/searcher/blines.rs
crates/maple_core/src/searcher/files.rs
crates/maple_core/src/searcher/grep.rs
crates/maple_core/src/stdio_server/handler/on_create.rs
crates/maple_core/src/stdio_server/provider/filer.rs
crates/maple_core/src/stdio_server/provider/generic_provider.rs
crates/maple_core/src/stdio_server/provider/mod.rs
crates/maple_core/src/stdio_server/provider/recent_files.rs
crates/printer/src/lib.rs
crates/printer/src/trimmer/v1.rs
crates/printer/src/truncation.rs
pythonx/clap/fuzzymatch-rs/Cargo.lock
pythonx/clap/fuzzymatch-rs/src/lib.rs

By converting the match indice from char-position to byte-position.

Fix trim text panic

---

autoload/clap.vim
autoload/clap/themes.vim
crates/maple_core/src/config.rs
crates/maple_core/src/datastore/mod.rs
crates/maple_core/src/tools/gtags/mod.rs

To have a better default display highlight for neovim.

Change default highlight of display to `ClapDefaultPreview`

---

autoload/clap.vim
autoload/clap/indicator.vim
autoload/clap/legacy/dispatcher.vim
autoload/clap/legacy/job/regular/maple.vim
autoload/clap/provider/blines.vim
autoload/clap/provider/buffers.vim
autoload/clap/provider/filer.vim
autoload/clap/provider/live_grep.vim
autoload/clap/selection.vim
autoload/clap/sign.vim
autoload/clap/state.vim
crates/maple_core/src/find_usages/search_engine/ctags/mod.rs
crates/maple_core/src/find_usages/search_engine/mod.rs
crates/maple_core/src/previewer/mod.rs
crates/maple_core/src/stdio_server/handler/on_move.rs
crates/maple_core/src/stdio_server/provider/dumb_jump/mod.rs
crates/maple_core/src/stdio_server/provider/dumb_jump/searcher.rs
crates/maple_core/src/stdio_server/provider/filer.rs
crates/maple_core/src/stdio_server/provider/recent_files.rs
crates/utils/src/io.rs

A sign to indicate the number of selected items is added.

Rework indicator sign

---

autoload/clap/popup/move_manager.vim

Support `<C-W>` for Vim Popup

---

README.md
autoload/clap.vim
autoload/clap/api.vim
autoload/clap/provider/grep.vim
crates/cli/src/command/grep/mod.rs
crates/maple_core/src/searcher/blines.rs
crates/maple_core/src/searcher/files.rs
crates/maple_core/src/searcher/grep/stoppable_searcher.rs
crates/maple_core/src/searcher/mod.rs
crates/maple_core/src/stdio_server/provider/grep.rs
crates/maple_core/src/stdio_server/provider/mod.rs
crates/maple_core/src/stdio_server/vim.rs

Support searching multiple directories for `grep` provider

---

Cargo.lock
autoload/clap/client.vim
crates/maple_core/src/find_usages/search_engine/regex/executable_searcher.rs
crates/maple_core/src/paths.rs
crates/maple_core/src/searcher/grep/stoppable_searcher.rs
crates/maple_core/src/stdio_server/provider/recent_files.rs
crates/maple_core/src/tools/rg/mod.rs
crates/printer/Cargo.toml
crates/printer/src/lib.rs
crates/printer/src/trimmer/v1.rs
crates/printer/src/truncation.rs
crates/types/src/source_item.rs
syntax/clap_grep.vim

Preserve the file name when truncating the grep results

---

PROVIDER.md
autoload/clap/popup/move_manager.vim
autoload/clap/provider/filer.vim
crates/maple_core/src/stdio_server/provider/filer.rs
crates/maple_core/src/stdio_server/provider/mod.rs

Use different ClapItem impl for FilerItem

---

autoload/clap/client.vim
autoload/clap/helper.vim
crates/maple_core/src/cache/mod.rs
crates/maple_core/src/stdio_server/handler/on_initialize.rs
crates/maple_core/src/stdio_server/provider/generic_provider.rs
crates/maple_core/src/stdio_server/provider/mod.rs
crates/printer/src/truncation.rs

Make sure the source initialization is complete for list-style providers

---

crates/maple_core/src/config.rs
crates/maple_core/src/find_usages/search_engine/regex/definition.rs
crates/maple_core/src/find_usages/search_engine/regex/executable_searcher.rs
crates/maple_core/src/find_usages/search_engine/regex/mod.rs
crates/maple_core/src/stdio_server/handler/on_initialize.rs
crates/maple_core/src/stdio_server/handler/on_move.rs
crates/maple_core/src/stdio_server/input.rs
crates/maple_core/src/stdio_server/provider/blines.rs
crates/maple_core/src/stdio_server/provider/files.rs
crates/maple_core/src/stdio_server/provider/generic_provider.rs
crates/maple_core/src/stdio_server/provider/grep.rs
crates/maple_core/src/stdio_server/provider/mod.rs
crates/maple_core/src/stdio_server/provider/recent_files.rs
crates/maple_core/src/stdio_server/provider/tagfiles.rs
crates/maple_core/src/stdio_server/service.rs
crates/upgrade/src/github.rs
crates/upgrade/src/lib.rs

Add --query for all providers

---

crates/maple/Cargo.toml
crates/maple/src/main.rs

Fix https://github.com/termux/termux-packages/issues/20063

Fix build for Android

---

Cargo.lock
crates/filter/src/sequential_worker.rs
crates/maple_config/doc_gen/src/main.rs
crates/maple_config/src/lib.rs
crates/maple_core/src/stdio_server/plugin/mod.rs
crates/maple_derive/tests/tests.rs
crates/printer/src/trimmer/v0.rs
crates/printer/src/truncation.rs
rust-toolchain.toml

Update to rust 1.80

---

autoload/clap/selection.vim
autoload/clap/util.vim
crates/maple_core/src/stdio_server/input.rs
crates/maple_core/src/stdio_server/provider/impls/filer.rs
crates/maple_core/src/stdio_server/provider/impls/igrep.rs

Fix open action regression for filer provider
